### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by sridhar02** [sridhar02/science-project#1]
Backend
- [x] Endpoint accepts image
- [x] Endpoint for openai call
- [x] R2 image upload
- [ ] KV per day calls storage
- [x] prompt 

Frontend
- [x] password field 
- [x] local storage check
- [x] Image upload button
- [x] camera image capture
- [x] Multi-part form data to worker
- [x] Image preview (optional)
- [x] Loading state
- [x] solution/ Graded answer
